on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - develop-*
      - release/**
      - epic/**
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
  
env:
  NODE_VERSION: '16'
  NX_BASE: origin/${{ github.event.pull_request.base.ref }}
  NX_HEAD: origin/${{ github.event.pull_request.head.ref }}

concurrency: 
  group: ci-continuous-integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Continuous Integration
jobs:
  linting:
    name: asdadasd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.event.pull_request.base.sha }}
          restore-keys: nodemodules-${{ github.event.pull_request.base.sha }}
      - name: Package installation
        run: npm ci
      - name: Run linting validation
        run: |
          ci-scripts/abctest.sh
