on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - develop-*
      - release/**
      - epic/**
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
  
env:
  NODE_VERSION: '16'

concurrency: 
  group: ci-continuous-integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: abc terst
jobs:
  no_retries:
    name: Verify re-run of all jobs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Context Info:"
          echo "  Event = ${{ github.event_name }}"
          echo "  Branch = ${{ github.ref_name }}"
          echo " base = ${{ github.base_ref }}"
          echo " head = ${{ github.head_ref }}"
          echo " 1 = ${{ github.event.pull_request.base.ref }}"
          echo " 2 = ${{ github.event.pull_request.head.ref }}"
          echo " 3 = ${{ github.event.pull_request.base.sha }}"
          echo " 4 = ${{ github.event.pull_request.head.sha }}"
      - name: ok
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
