on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
  
concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Spartacus build pipeline
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - run: yarn install --frozen-lockfile
      - run: npx add-nx-to-monorepo@latest
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx print-affected
      - run: npx nx print-affected --base=develop --head=HEAD
