on:
  push:
    branches:
      - develop
      - develop-*
      - release/**
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow

env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
  NODE_VERSION: '16'

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Spartacus build pipeline
jobs:
  no_retries:
    name: Verify re-run of all jobs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Context Info:"
          echo "  Event = ${{ github.event_name }}"
          echo "  Branch = ${{ github.ref_name }}"
          echo " base = ${{ github.base_ref }}"
          echo " head = ${{ github.head_ref }}"
          echo " 1 = ${{ github.event.pull_request.base.ref }}"
          echo " 2 = ${{ github.event.pull_request.head.ref }}"
      - name: ok
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: echo "$GITHUB_CONTEXT"
