on:
  pull_request:
    types: [opened, synchronize]

concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Prepend licences to files
jobs:
  prepend_license: 
    name: Commit prepended licences to files 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download reuse tool
        run: pip3 install --user reuse
      - name: Setup git config for github bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get all files to license
        id: files-to-license
        run: |
          FILES=$(find . -not -path '**/node_modules/**' -not -name '*spec*' -name '*.ts' -print)
          echo "::set-output name=files::$(echo $FILES)"
      - name: Adding headers to files
        run: | 
          reuse addheader --copyright="SAP Spartacus team <spartacus-team@sap.com>" --license="Apache-2.0" --multi-line ${{ steps.files-to-license.outputs.files }}

      # - name: Using reuse tool to prepend headers to files
      #   uses: fsfe/reuse-action@v1
      #   with: 
      #     args: addheader --copyright="SAP Spartacus team <spartacus-team@sap.com>" --license="Apache-2.0" --multi-line ${{ steps.files-to-license.outputs.files }}
      - name: test
        run: |
          git add .
          git commit -m "prepend licences"
          git push
