on:
  pull_request:
    types: [opened, synchronize]

concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Prepend licences to files
jobs:
  prepend_license: 
    name: Commit prepended licences to files 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git config for github bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get all files to license
        id: files-to-license
        run: echo "::set-output name=files::$(find . -not -path '**/node_modules/**' -not -name '*spec*' -name '*.ts' -print)"
      - name: test
        run: echo ${{ steps.files-to-license.outputs.files }}
