on:
  pull_request:
    types: [opened, synchronize]

concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Prepend licences to files
jobs:
  prepend_license: 
    name: Commit prepended licences to files 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download reuse tool
        run: pip3 install --user reuse
      - name: Setup git config for github bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Adding headers to files
        run: ci-scripts/prepend-license.sh
      - name: push a commit to current pull request
        run: |
          if [ -z $(git status --porcelain) ];
          then
              echo "No files to commit"
          else
              git add .
              git commit -m "Prepend licence to files"
              git push
          fi
