on:
  pull_request
name: "Pull Request Labeler"
jobs:
  autoLabelPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v3
      with: 
        configuration-path: .github/pull-request.labeler.yml
      env:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"