on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  # push:
  #   branches:
  #     - develop
name: "Publish Release Draft notes"
jobs:
  preReleaseDraft:
    name: Create pre-release draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create changelogs
        id: changelog
        run: |
          please=$(ts-node scripts/changelog.ts --verbose --from asm-4.0.0)
          echo "wow $please"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_TAG: 'user-4.1.1'
          TO_TAG: 'HEAD'
      - name: Stuff from changelog
        run: |
          echo ${{ steps.changelog.outputs.changelog }}