on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'x.x.x'
        required: true
        default: 4.2.0
      fromTag:
        description: 'previous release tag version'
        required: true
        default: 'asm-3.4.3'
      toTag:
        description: 'current release tag version'
        required: true
        default: 'asm-4.0.0'
name: "Release"
jobs:
  setup: 
    name: setup dependencies
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Set Spartacusbot
        run: |
          git config user.name "Spartacus[bot]"
          git config user.email "spartacus-sap@github.com"
  preRelease:
    name: Create pre-release 
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: create changelogs
        id: changelog
        run: npx lerna-changelog --tag-from ${{ github.event.inputs.fromTag }} --tag-to ${{ github.event.inputs.toTag }}
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish pre-release
        uses: ./.github/publish-pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          TAG: ${{ github.event.inputs.toTag }} 
      