on:
  push:
    branches:
      - develop
name: "Publish Release Draft notes"
jobs:
  setup: 
    name: setup dependencies
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
  preReleaseDraft:
    name: Create pre-release draft
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Create changelogs
        id: changelog
        uses: ./.github/generate-changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          FROM_TAG: 'user-4.1.1'
          TO_TAG: 'HEAD'
      - name: Stuff from changelog
        run: |
          echo ${{ steps.changelog.outputs.changelog }}