on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:
    inputs:
      FROM_TAG:
        description: 'previous release tag version'
        default: '3.0.0-test'
      TO_TAG:
        description: 'current release tag version'
        default: '5.0.0-test'
name: "Publish Release Draft notes"
jobs:
  preReleaseDraft:
    name: Create pre-release draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create changelogs
        id: changelog
        uses: ./.github/generate-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_TAG: ${{ github.event.inputs.FROM_TAG }}
          TO_TAG: ${{ github.event.inputs.TO_TAG }}
      - name: Create release draft
        uses: ./.github/publish-release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          TO_TAG: ${{ github.event.inputs.TO_TAG }}