on:
  push:
    branches:
      - develop
    schedule:
    - cron:  '0 0 * * 1,3'
  workflow_dispatch:

name: Sync develop branch to private PWA repo

jobs:
  sync_public_repo_to_private:
    name: Force sync the develop branch to the private repository with current git history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: push develop branch to the private repository
        run: | 
          git push -u https://I506207:${{secrets.BRIAN_PRIVATE_SYNC_TEST_PWA}}@github.tools.sap/cx-commerce/second-spartacus-test.git develop -f
