on:
  push:
    branches:
      - wow

name: test stuff

jobs:
  testing_stuff:
    name: stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: testing
        run: |
          ci-scripts/push-new-commits.sh
